teckit_compile  math-italic
teckit_compile  math-bold
teckit_compile  math-italic-bold
teckit_compile  math-script
teckit_compile  math-script-bold
teckit_compile  math-blackboard
teckit_compile  math-fraktur
teckit_compile  math-fraktur-bold
teckit_compile  math-sans
teckit_compile  math-sans-bold
teckit_compile  math-sans-italic
teckit_compile  math-sans-italic-bold
teckit_compile  math-typewriter
