(TeX-add-style-hook "pfuconf"
 (lambda ()
    (LaTeX-add-environments
     "titlepage"
     "altabstract")
    (LaTeX-add-labels
     "#1"
     "#2"
     "altaddress:#2"
     "starttitle")
    (TeX-add-symbols
     '("urladdr" ["argument"] 1)
     '("email" ["argument"] 1)
     '("altabstracts" ["argument"] 1)
     '("subtitle" ["argument"] 1)
     '("alttitle" ["argument"] 1)
     '("tocsection" 3)
     '("defaultaltlanguage" 1)
     '("defaultlanguage" 1)
     '("nxandlist" 4)
     '("xandlist" 4)
     '("nxaltandlist" 4)
     '("xaltandlist" 4)
     '("uppercasenonmath" 1)
     '("pacs" 1)
     '("udc" 1)
     "linespacing"
     "normalparindent"
     "upchars"
     "andify"
     "altandify"
     "titleFontShape"
     "titleFontSize"
     "titlePosition"
     "altabstractname"
     "bibindent"
     "chapaftersnum"
     "secaftersnum"
     "subchapter"
     "baselinestretch"
     "label"
     "ref"
     "pageref"
     "glabel"
     "gref"
     "gpageref"
     "theHaddress"
     "thanksref"
     "runtitle"
     "runauthor"
     "cauthor"
     "altauthor"
     "caltauthor"
     "parseauthor"
     "authorinitials"
     "authorfamily"
     "PFUNumRunningauthor"
     "collab"
     "collaboration"
     "thefootnote"
     "theaddress"
     "altaddress"
     "thealtaddress"
     "authorsrunning"
     "altauthorsrunning"
     "altauthorstoc"
     "makesubtitle"
     "shortsubtitle"
     "shortaltauthors"
     "altauthors"
     "altaddresses"
     "ss"
     "i"
     "j"
     "ae"
     "oe"
     "o"
     "aa"
     "l"
     "Mc"
     "author"
     "address"
     "curraddr"
     "email"
     "urladdr"
     "dedicatory"
     "keywords"
     "subjclass"
     "translator"
     "and"
     "altand"
     "maketitle"
     "shorttitle"
     "shortauthors"
     "authors"
     "authorstoc"
     "addresses"
     "thankses"
     "publname"
     "volinfo"
     "issueinfo"
     "currentvolume"
     "currentissue"
     "currentmonth"
     "currentyear"
     "copyrightinfo"
     "copyrightyear"
     "copyrightholder"
     "pagespan"
     "thanks"
     "fullwidthdisplay"
     "tableofcontents"
     "listoffigures"
     "listoftables"
     "listofalts"
     "indentlabel"
     "tocsubsection"
     "tocsubsubsection"
     "tocpart"
     "tocchapter"
     "tocappendix"
     "refname"
     "bibname"
     "bibliographystyle"
     "bibsetup"
     "PFUrevisedName"
     "PFUacceptedName"
     "PFUpublishedName"
     "PFUudcName"
     "PFUpacsName"
     "PFUreceivedName"
     "PFUrevisedname"
     "PFUacceptedname"
     "PFUpublishedname"
     "etal"
     "keywordsname"
     "calclayout"
     "tiny"
     "defaultfont"
     "rom")
    (TeX-run-style-hooks
     "titletoc"
     "truncate"
     "ifthen"
     "titlesec"
     "kgeneric10"
     "kgeneric")))

