(TeX-add-style-hook "kproc"
 (lambda ()
    (LaTeX-add-environments
     "theindex"
     "titlepage"
     "altabstract"
     "abstract"
     "abstracta")
    (LaTeX-add-labels
     "#1"
     "starttitle"
     "address:#2"
     "altaddress:#2"
     "endtitle")
    (TeX-add-symbols
     "endverse"
     '("urladdr" ["argument"] 1)
     '("email" ["argument"] 1)
     '("altcurraddr" ["argument"] 1)
     '("curraddr" ["argument"] 1)
     '("alttitle" ["argument"] 1)
     '("altappendixtitle" ["argument"] 1)
     '("appendixtitle" ["argument"] 1)
     '("subtitle" ["argument"] 1)
     '("see" 2)
     '("MR" 1)
     '("tocsection" 3)
     '("altabstracts" 1)
     '("abstracts" 1)
     '("nxandlist" 4)
     '("xandlist" 4)
     '("nxaltandlist" 4)
     '("xaltandlist" 4)
     '("dedicatory" 1)
     '("thanksref" 1)
     '("published" 1)
     '("accepted" 1)
     '("revised" 1)
     '("received" 1)
     '("pacs" 1)
     '("udc" 1)
     '("uppercasenonmath" 1)
     '("defaultaltlanguage" 1)
     '("defaultlanguage" 1)
     "linespacing"
     "normalparindent"
     "normaltopskip"
     "headerFontSize"
     "upchars"
     "andify"
     "altandify"
     "makealttitle"
     "makealttitleTOCOnly"
     "subjclassname"
     "altabstractname"
     "listisep"
     "chapaftersnum"
     "secaftersnum"
     "tableofaltcontents"
     "bibindent"
     "URL"
     "abovecaptionskip"
     "belowcaptionskip"
     "captionindent"
     "printindex"
     "textprime"
     "theHaddress"
     "thanksref"
     "runtitle"
     "runauthor"
     "baselinestretch"
     "sectionname"
     "subsectionname"
     "subsubsectionname"
     "paragraphname"
     "subparagraphname"
     "markboth"
     "sectionmark"
     "subsectionmark"
     "subsubsectionmark"
     "paragraphmark"
     "ProcessClassOptionsWithKV"
     "series"
     "SetPFUprocKey"
     "label"
     "ref"
     "pageref"
     "glabel"
     "gref"
     "gpageref"
     "PFUrevisedName"
     "PFUacceptedName"
     "PFUpublishedName"
     "PFUudcName"
     "PFUpacsName"
     "PFUreceivedName"
     "PFUrevisedname"
     "PFUacceptedname"
     "PFUpublishedname"
     "etal"
     "keywordsname"
     "prefacename"
     "abstractname"
     "chaptername"
     "authorname"
     "enclname"
     "ccname"
     "headtoname"
     "pagename"
     "seename"
     "alsoname"
     "proofname"
     "glossaryname"
     "ss"
     "i"
     "j"
     "ae"
     "oe"
     "o"
     "aa"
     "l"
     "Mc"
     "authorsrunning"
     "altauthorsrunning"
     "author"
     "altauthor"
     "fauthor"
     "cauthor"
     "altfauthor"
     "caltauthor"
     "parseauthor"
     "authorinitials"
     "authorfamily"
     "PFUNumRunningauthor"
     "collab"
     "collaboration"
     "thefootnote"
     "theaddress"
     "altaddress"
     "thealtaddress"
     "address"
     "curraddr"
     "email"
     "urladdr"
     "dedicatorywidth"
     "keywords"
     "altkeywords"
     "subjclass"
     "translator"
     "and"
     "altand"
     "maketitle"
     "shorttitle"
     "makeappendixtitle"
     "makesubtitle"
     "shortsubtitle"
     "shortauthors"
     "authors"
     "authorstoc"
     "shortaltauthors"
     "altauthors"
     "altauthorstoc"
     "altaddresses"
     "thankses"
     "addresses"
     "publname"
     "volinfo"
     "issueinfo"
     "currentvolume"
     "currentissue"
     "currentmonth"
     "currentyear"
     "copyrightinfo"
     "copyrightyear"
     "copyrightholder"
     "pagespan"
     "thanks"
     "trivlist"
     "makelabel"
     "upn"
     "partname"
     "appendixname"
     "aufm"
     "contentsname"
     "altcontentsname"
     "listfigurename"
     "listtablename"
     "listaltname"
     "listoffigures"
     "listoftables"
     "listofalts"
     "indentlabel"
     "tocsubsection"
     "tocsubsubsection"
     "tocchapter"
     "tocappendix"
     "refname"
     "bibname"
     "bysame"
     "newblock"
     "URLhref"
     "item"
     "indexname"
     "subitem"
     "subsubitem"
     "indexspace"
     "footnoterule"
     "sloppy"
     "figurename"
     "subfigure"
     "tablename"
     "nonbreakingspace"
     "fullwidthdisplay"
     "calclayout"
     "tiny"
     "defaultfont"
     "rom")
    (TeX-run-style-hooks
     "subfig"
     "titlesec"
     "fancyhdr"
     "truncate"
     "ltcaption"
     "caption"
     "array"
     "ltxgrid"
     "longtable"
     "kgeneric10"
     "kgeneric"
     "xifthen"
     "substr"
     "keyval"
     "etextools")))

